name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test-check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # TODO: check more operating systems?
        compiler:
          - "ghc802"
          - "ghc822"
          - "ghc844"
          - "ghc865"
          - "ghc883"
          - "ghc8101"

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        # with: nixpath=./nixpkgs?

      # - name: Setup cabal cache
      #   uses: actions/cache@v1
      #   with:
      #     path: "~/.cabal"
      #     key: "${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('kesha.cabal') }}"

      # TODO: cachix the ghc builds coming from this?
      - name: Run ci.sh
        run: "nix-shell --argstr compiler ${{ matrix.compiler }} --arg dev false --run ./ci.sh"
